### ISSUE TITLE
RestClient should implement IDisposable (and Dispose(bool) from HttpClient)

### ISSUE THREAD

**Issue by killswtch** [CloudNimble/PortableRest#45]
HttpClient is disposable, as it deals with unmanaged resources, however it cannot currently be desposed by applications using PortableRest since RestClient doesn't implement IDisposable. This has the potential to cause issues in some circumstances where RestClient instances are rapidly created and discarded (but not disposed).

**Comment by nikhilagrawaldotnet** [comment]
What happened to IDisposable? Did it never made to release version?
